Repository bids-standard/bids-validator, pull requests merged in 2019-02, with the labels that each got.

#711 Showcase contributors
  README.md
Labels: enhancement

#681 [MRG] remove optional arguments bep006 and bep010
  bids-validator/bin/bids-validator
  bids-validator/tests/utils/issues.spec.js
  bids-validator/utils/modalities.js
  bids-validator/utils/options.js
  bids-validator/utils/summary/collectSessions.js
  bids-validator/utils/summary/collectSubjects.js
  bids-validator/utils/type.js
  bids-validator/validators/bids/groupFileTypes.js
  bids-validator/validators/bids/quickTest.js
  bids-validator/validators/bids/start.js
Labels: EEG, iEEG

#678 [MRG] EEG fixes while merging into main spec
  bids-validator/tests/json.spec.js
  bids-validator/validators/json/schemas/eeg.json
Labels: EEG

#599 [MRG] add non-custom events columns
  bids-validator/bids_validator/tsv/non_custom_columns.json
Labels: EEG, iEEG
