Repository bids-standard/bids-validator, pull requests merged in 2024-05, with the labels that each got.

#1956 fix(expressions): Make FileTree.contains() return true for directories
  bids-validator/src/types/filetree.ts
Labels: schema

#1951 FIX: Start file count at 0
  bids-validator/src/summary/summary.ts
Labels: schema

#1964 feat(legacy): Check for required fields in PET sidecars.
  bids-validator/utils/issues/list.js
  bids-validator/validators/nifti/__tests__/nii.spec.js
  bids-validator/validators/nifti/nii.js
Labels: legacy

#1967 feat(py): Base Python validator on schema instead of hard-coded regexes
  .circleci/config.yml
  bids-validator/bids_validator/bids_validator.py
  bids-validator/bids_validator/test_bids_validator.py
  bids-validator/pyproject.toml
  bids-validator/setup.cfg
Labels: python, schema
